version: '3.8'

services:
  web:
    build: .
    command: make app-start
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
